### ISSUE TITLE
Problema Base de Datos

### ISSUE THREAD

**Issue by MegaDangerss** [ElevenProyecto1DAW2/ElevenProyecto1#1]
Nos olvidamos de poner autoincrement en las primary keys por lo tanto no se podía añadir más de un registro en la base de datos

**Comment by AdrianMartinViorreta** [comment]
Hemos cambiado la base de datos, uniendo las tablas equipos y salas en 1 sola y hemos fusionado la realcion entre esta y usuario, además hemos creado una tabla intermedia que era incidencias
